# Schmidt et al. 2024 (DOI: 10.1186/s12864-024-10013-x)
# Fig S9

#Download Packages
library(Seurat)
library(patchwork)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(lubridate)
library(RColorBrewer)
library(enrichR)
library(Matrix)
library(circlize)
library(ComplexHeatmap)
library(gplots)
library(scales)
library(EnhancedVolcano)
library(tidyverse)
library(scclusteval)
library(singleseqgset)
library(heatmap3)
library(SCopeLoomR)
library(AUCell)
library(SCENIC)
library(fmsb)
library(tidyverse)
library(SeuratWrappers)
library(monocle3)
library(data.table)

## Downloading Beta Data
setwd("")
endocrine_integrated = readRDS('endocrine_integrated.rds')
all_beta = subset(endocrine_integrated, endocrine_identity %in% "Beta")
sc_adult_fetal_beta = subset(all_beta, maturation %in% c("SC-Vitro", "Adult","Fetal"))

## Figure S9A & S9B were generated by running the same SCENIC Analysis as in Fig4
## The 50 most highly expressed targets of some of the most active TFs in SC-Beta cells were retrieved
## These genes were submitted to the Enrichr web interface at https://maayanlab.cloud/Enrichr/

## Add Regulon Data to Seurat Object
AUCmat <- AUCell::getAUC(regulonAUC)
sc_adult_fetal_beta[["AUC"]] <- CreateAssayObject(data = AUCmat)
DefaultAssay(sc_adult_fetal_beta) <- "AUC"
sc_adult_fetal_beta <- ScaleData(sc_adult_fetal_beta, assay = "AUC")

## SOX4 Top 50 regulons
DefaultAssay(sc_adult_fetal_beta) = "RNA"
Idents(sc_adult_fetal_beta) = "maturation"
sox4_targets = regulons[["SOX4(+)"]]
sox4_avg_expression = AverageExpression(sc_adult_fetal_beta, features = sox4_targets)
sox4_avg_expression = sox4_avg_expression[1]
sox4_avg_expression = as.data.frame(sox4_avg_expression)
sox4_avg_expression <- sox4_avg_expression[1]
sox4_avg_expression<-sox4_avg_expression[order(sox4_avg_expression$RNA.SC.Vitro,decreasing=TRUE),,drop=F]
sox4_top_50_expressed_genes = rownames(sox4_avg_expression)
sox4_top_50_expressed_genes = sox4_top_50_expressed_genes[1:50]

## SOX11 Top 50 regulons
sox11_targets = regulons[["SOX11(+)"]]
sox11_avg_expression = AverageExpression(sc_adult_fetal_beta, features = sox11_targets)
sox11_avg_expression = sox11_avg_expression[1]
sox11_avg_expression = as.data.frame(sox11_avg_expression)
sox11_avg_expression <- sox11_avg_expression[1]
sox11_avg_expression<-sox11_avg_expression[order(sox11_avg_expression$RNA.SC.Vitro,decreasing=TRUE),,drop=F]
sox11_top_50_expressed_genes = rownames(sox11_avg_expression)
sox11_top_50_expressed_genes = sox11_top_50_expressed_genes[1:50]

## OCT7 Top 50 regulons
oct7_targets = regulons[["POU3F2(+)"]]
oct7_avg_expression = AverageExpression(sc_adult_fetal_beta, features = oct7_targets)
oct7_avg_expression = oct7_avg_expression[1]
oct7_avg_expression = as.data.frame(oct7_avg_expression)
oct7_avg_expression <- oct7_avg_expression[1]
oct7_avg_expression<-oct7_avg_expression[order(oct7_avg_expression$RNA.SC.Vitro,decreasing=TRUE),,drop=F]
oct7_top_50_expressed_genes = rownames(oct7_avg_expression)
oct7_top_50_expressed_genes = oct7_top_50_expressed_genes[1:50]

## PBX1 Top 50 regulons
pbx1_targets = regulons[["PBX1(+)"]]
pbx1_avg_expression = AverageExpression(sc_adult_fetal_beta, features = pbx1_targets)
pbx1_avg_expression = pbx1_avg_expression[1]
pbx1_avg_expression = as.data.frame(pbx1_avg_expression)
pbx1_avg_expression <- pbx1_avg_expression[1]
pbx1_avg_expression<-pbx1_avg_expression[order(pbx1_avg_expression$RNA.SC.Vitro,decreasing=TRUE),,drop=F]
pbx1_top_50_expressed_genes = rownames(pbx1_avg_expression)
pbx1_top_50_expressed_genes = pbx1_top_50_expressed_genes[1:50]

## FOXA2 Top 50 regulons
foxa2_targets = regulons[["FOXA2(+)"]]
foxa2_avg_expression = AverageExpression(sc_adult_fetal_beta, features = foxa2_targets)
foxa2_avg_expression = foxa2_avg_expression[1]
foxa2_avg_expression = as.data.frame(foxa2_avg_expression)
foxa2_avg_expression <- foxa2_avg_expression[1]
foxa2_avg_expression<-foxa2_avg_expression[order(foxa2_avg_expression$RNA.SC.Vitro,decreasing=TRUE),,drop=F]
foxa2_top_50_expressed_genes = rownames(foxa2_avg_expression)
foxa2_top_50_expressed_genes = foxa2_top_50_expressed_genes[1:50]

## EBF1 Top 50 regulons
ebf1_targets = regulons[["EBF1(+)"]]
ebf1_avg_expression = AverageExpression(sc_adult_fetal_beta, features = ebf1_targets)
ebf1_avg_expression = ebf1_avg_expression[1]
ebf1_avg_expression = as.data.frame(ebf1_avg_expression)
ebf1_avg_expression <- ebf1_avg_expression[1]
ebf1_avg_expression<-ebf1_avg_expression[order(ebf1_avg_expression$RNA.SC.Vitro,decreasing=TRUE),,drop=F]
ebf1_top_50_expressed_genes = rownames(ebf1_avg_expression)
ebf1_top_50_expressed_genes = ebf1_top_50_expressed_genes[1:50]